tejidos_dict = {
    "Tejido Adiposo": "adipose tissue",
    "Médula Ósea": "bone marrow",
    "Cerebro": "brain",
    "Mama": "breast",
    "Bronquio": "bronchus",
    "Colon": "colon",
    "Endometrio": "endometrium",
    "Esófago": "esophagus",
    "Ojo": "eye",
    "Trompa de Falopio": "fallopian tube",
    "Músculo Cardíaco": "heart muscle",
    "Riñón": "kidney",
    "Hígado": "liver",
    "Pulmón": "lung",
    "Ganglio Linfático": "lymph node",
    "Ovario": "ovary",
    "Páncreas": "pancreas",
    "PBMC": "pbmc",
    "Placenta": "placenta",
    "Próstata": "prostate",
    "Recto": "rectum",
    "Glándula Salival": "salivary gland",
    "Músculo Esquelético": "skeletal muscle",
    "Piel": "skin",
    "Intestino Delgado": "small intestine",
    "Bazo": "spleen",
    "Estómago": "stomach",
    "Testículo": "testis",
    "Timo": "thymus",
    "Lengua": "tongue",
    "Vascular": "vascular"
}
