tejidos_dict = {
    "Adipose Tissue": "Tejido Adiposo",
    "Bone Marrow": "Médula Ósea",
    "Brain": "Cerebro",
    "Breast": "Mama",
    "Bronchus": "Bronquio",
    "Colon": "Colon",
    "Endometrium": "Endometrio",
    "Esophagus": "Esófago",
    "Eye": "Ojo",
    "Fallopian Tube": "Trompa de Falopio",
    "Heart Muscle": "Músculo Cardíaco",
    "Kidney": "Riñón",
    "Liver": "Hígado",
    "Lung": "Pulmón",
    "Lymph Node": "Ganglio Linfático",
    "Ovary": "Ovario",
    "Pancreas": "Páncreas",
    "PBMC": "PBMC",
    "Placenta": "Placenta",
    "Prostate": "Próstata",
    "Rectum": "Recto",
    "Salivary Gland": "Glándula Salival",
    "Skeletal Muscle": "Músculo Esquelético",
    "Skin": "Piel",
    "Small Intestine": "Intestino Delgado",
    "Spleen": "Bazo",
    "Stomach": "Estómago",
    "Testis": "Testículo",
    "Thymus": "Timo",
    "Tongue": "Lengua",
    "Vascular": "Vascular",
}
